# Generated by Django 4.0.1 on 2022-02-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog-image/'),
        ),
    ]
